"""empty message

Revision ID: 5e49d3020951
Revises: fcaed8a7c6ee
Create Date: 2020-05-29 20:19:53.340959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e49d3020951'
down_revision = 'fcaed8a7c6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movies', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    # ### end Alembic commands ###
